Shortify/Models/Links.cs
using System.ComponentModel.DataAnnotations;

namespace Shortify.Models
{
    public class Links
    {
        [Key, Url]
        public string ShortLink { get; set; }
        [Url]
        public string LongLink { get; set; }
    }
}

Shortify/Controllers/RedirectController.cs
using Microsoft.AspNetCore.Mvc;
using Shortify.Context;
using Shortify.Models;
using System;
using System.Security.Policy;
using System.Threading.Tasks;

namespace Shortify.Controllers
{
    [Route("/[controller]")]
    [ApiController]
    public class RedirectController : ControllerBase
    {
        private readonly ContextLinks _context; 
        public RedirectController(ContextLinks context)
        {
            _context = context;
        }
        // GET /things
        [HttpGet("/{ShortLink}")]
        public async Task<IActionResult> Get([FromRoute]string ShortLink)
        {
            Links temp =await _context.Links.FindAsync(ShortLink);
            UriBuilder uri = new UriBuilder(temp.LongLink);
            return (temp != null) ? Redirect(uri.ToString()) : BadRequest("There isn't");
        }

    }
}

Shortify/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shortify.Context;
using Shortify.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Shortify.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ContextLinks _context;
        public string redirect { get; set; }
        public IndexModel(ContextLinks context)
        {
            _context = context;
        }

        public void OnGet()
        {
            redirect = "";
        }
        public async Task OnPostAsync(string link)
        {
            Links temp = _context.Links.Where(i => i.LongLink == link).SingleOrDefault();
            if (link!="" && temp == null)
            {
                Links links = new Links() { ShortLink = GenerateShort(), LongLink = link };
                await _context.Links.AddAsync(links);
                await _context.SaveChangesAsync();
                redirect = links.ShortLink;
            }
            else
            {
                redirect = temp.ShortLink;
            }

        }
        private string GenerateShort()
        {
            string url = "";
            Enumerable.Range(48, 75).Where(i => i < 58 || i > 64 && i < 91 || i > 96).OrderBy(o => new Random().Next()).ToList().ForEach(i => url += Convert.ToChar(i));
            return url.Substring(new Random().Next(0, url.Length), new Random().Next(2, 6));
            //if this code crush, i will be stuiped
        }
    }
}

Shortify/Pages/Index.cshtml
@page 
@model IndexModel
@using Models
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-3 text-lg-center" style="border-block-end">Shortify</h1>
    <content class="justify-content-center ">
        <table class="table d-table-row table-borderless">
            <thead></thead>
            <tbody class="">
                <tr>
                    <td class="border-right border-dark w-auto">
                        @if (Model.redirect != "")
                        {
                            <p>Clicking to redirect <a asp-controller="Redirect" asp-action="Get" asp-route-ShortLink=@Model.redirect target="_blank">Link</a>.</p>
                        }
                        else
                        {
                            <p></p>
                        }
                        <form method="POST">
                            <div>
                                <p>
                                    @if (Model.redirect != "")
                                    {
                                        <input name="link" class="form-control" placeholder="You can input URL" value="@(HttpContext.Request.Host +"/"+Model.redirect)" />
                                    }
                                    else
                                    {
                                        <input name="link" class="form-control" placeholder="You can input URL" value="@Model.redirect" />
                                    }
                                </p>
                            </div>
                            <div>
                                <p>
                                    <input class="btn btn-primary float-md-right" type="submit" value="Send" />
                                </p>
                            </div>
                        </form>
                    </td>
                    <td>
                        <div>
                            <h4 class="font-weight-normal" style="border-block-end">Why Shortify?</h4>
                            <ul>
                                <li>
                                    <h6 class="text-left font-weight-normal" style="border-block-end">Our name is similar to Spotify</h6>
                                </li>
                                <li>
                                    <h6 class="text-left font-weight-normal" style="border-block-end">We are free, but Spotify is not</h6>
                                </li>
                                <li>
                                    <h6 class="text-left font-weight-normal" style="border-block-end">Our page is minimalistic</h6>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </content>
</div>

Shortify/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shortify</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Shortify</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 Shortify
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>